name: Moremen Control Panel
on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target Link'
        required: true
      service_type:
        description: 'Service'
        required: true
      quantity:
        description: 'Amount'
        default: '1000'

jobs:
  phantom_task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Engine
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
          SERVICE: ${{ github.event.inputs.service_type }}
        run: python bot.py
        
